import type { CommandDef, CommandName } from "./types.js";

const COMMANDS: Record<CommandName, CommandDef> = {
  ping: {
    name: "ping",
    description: "Verifica conectividad con un host y mide latencia",
    template: "ping -c 4 {host}",
    example: "ping -c 4 192.168.1.1",
    riskLevel: "low",
    requiresHost: true,
    parser: "ping",
    timeout: 30_000,
    minArgs: 0,
    maxArgs: 0,
  },
  traceroute: {
    name: "traceroute",
    description: "Traza la ruta de paquetes hacia un destino",
    template: "traceroute -n {host}",
    example: "traceroute -n 8.8.8.8",
    riskLevel: "low",
    requiresHost: true,
    parser: "traceroute",
    timeout: 60_000,
    minArgs: 0,
    maxArgs: 0,
  },
  netstat: {
    name: "netstat",
    description: "Muestra puertos en escucha y conexiones activas",
    template: "netstat -tulpn 2>/dev/null || netstat -tulpn",
    example: "netstat -tulpn",
    riskLevel: "low",
    requiresHost: false,
    parser: "netstat",
    timeout: 15_000,
    minArgs: 0,
    maxArgs: 0,
  },
  ss: {
    name: "ss",
    description: "Estadísticas de socket (alternativa moderna a netstat)",
    template: "ss -tulpn",
    example: "ss -tulpn",
    riskLevel: "low",
    requiresHost: false,
    parser: "generic",
    timeout: 15_000,
    minArgs: 0,
    maxArgs: 0,
  },
  uptime: {
    name: "uptime",
    description: "Muestra el tiempo de actividad del sistema",
    template: "uptime",
    example: "uptime",
    riskLevel: "low",
    requiresHost: false,
    parser: "generic",
    timeout: 10_000,
    minArgs: 0,
    maxArgs: 0,
  },
  df: {
    name: "df",
    description: "Muestra el uso de disco",
    template: "df -h",
    example: "df -h",
    riskLevel: "low",
    requiresHost: false,
    parser: "generic",
    timeout: 10_000,
    minArgs: 0,
    maxArgs: 0,
  },
  free: {
    name: "free",
    description: "Muestra el uso de memoria",
    template: "free -m",
    example: "free -m",
    riskLevel: "low",
    requiresHost: false,
    parser: "generic",
    timeout: 10_000,
    minArgs: 0,
    maxArgs: 0,
  },
  host: {
    name: "host",
    description: "Resuelve un nombre de dominio a IPs",
    template: "host {host}",
    example: "host google.com",
    riskLevel: "low",
    requiresHost: true,
    parser: "dns",
    timeout: 15_000,
    minArgs: 0,
    maxArgs: 0,
  },
  nslookup: {
    name: "nslookup",
    description: "Resolución DNS de un dominio",
    template: "nslookup {host}",
    example: "nslookup google.com",
    riskLevel: "low",
    requiresHost: true,
    parser: "dns",
    timeout: 15_000,
  },
  dig: {
    name: "dig",
    description: "Resolución DNS detallada",
    template: "dig +short {host}",
    example: "dig +short google.com",
    riskLevel: "low",
    requiresHost: true,
    parser: "dns",
    timeout: 15_000,
  },
  curl: {
    name: "curl",
    description: "Verifica disponibilidad de un endpoint HTTP",
    template: "curl -o /dev/null -s -w 'HTTP_CODE:%{http_code} TIME:%{time_total}' {args} {host}",
    example: "curl -I https://192.168.1.10/health",
    riskLevel: "low",
    requiresHost: true,
    parser: "curl",
    timeout: 30_000,
  },
  nc: {
    name: "nc",
    description: "Verifica si un puerto TCP está abierto",
    template: "nc -zv -w 5 {host}",
    example: "nc -zv 192.168.1.10 443",
    riskLevel: "low",
    requiresHost: true,
    parser: "generic",
    timeout: 15_000,
  },
  "systemctl": {
    name: "systemctl",
    description: "Consulta el estado de un servicio del sistema",
    template: "systemctl status {args} 2>&1 || true",
    example: "systemctl status postgresql-15",
    riskLevel: "medium",
    requiresHost: false,
    parser: "service-status",
    timeout: 15_000,
    minArgs: 1,
    maxArgs: 3,
    allowedArgsPattern: /^[a-zA-Z0-9._@:-]+$/,
  },
  "redis-cli": {
    name: "redis-cli",
    description: "Verifica conectividad con Redis",
    template: "redis-cli -h {host} ping 2>&1 || echo 'ERROR'",
    example: "redis-cli -h 192.168.1.30 ping",
    riskLevel: "low",
    requiresHost: true,
    parser: "redis-ping",
    timeout: 15_000,
  },
  ip: {
    name: "ip",
    description: "Muestra interfaces de red y rutas",
    template: "ip addr show 2>/dev/null || ipconfig",
    example: "ip addr show",
    riskLevel: "low",
    requiresHost: false,
    parser: "generic",
    timeout: 10_000,
  },
  route: {
    name: "route",
    description: "Muestra la tabla de enrutamiento",
    template: "ip route 2>/dev/null || route print",
    example: "ip route",
    riskLevel: "low",
    requiresHost: false,
    parser: "generic",
    timeout: 10_000,
  },
  journalctl: {
    name: "journalctl",
    description: "Consulta logs recientes del sistema",
    template: "journalctl -n 50 --no-pager 2>&1 || echo 'No journalctl available'",
    example: "journalctl -u NetworkManager --since '1 hour ago' --no-pager",
    riskLevel: "low",
    requiresHost: false,
    parser: "generic",
    timeout: 15_000,
  },
};

export function getCommand(name: CommandName): CommandDef | undefined {
  return COMMANDS[name];
}

export function listCommands(): CommandDef[] {
  return Object.values(COMMANDS);
}

export function validateCommand(name: string): CommandDef | null {
  const cmd = COMMANDS[name as CommandName];
  return cmd ?? null;
}
